puts "The students of Cerulean City Gym"
puts "--------------"
puts "Misty"
puts "Daisy"
puts "Lily"
puts "Violet"
puts "Ash Ketchum"
puts "Aquaman"
puts "Jar Jar Binks"
puts "Ariel"
puts "Melody"

print "Overall, we have \n"
print 9
puts " great students"
